### ISSUE TITLE
What exactly is "zoom"?

### ISSUE THREAD

**Issue by swaheera** [yukai-yang/zoomgrid#1]
Hello!

Great job on this R package! I really like it!

I had some questions:

1) Just to clarify, this package performs the standard grid search and random grid search?

2) What exactly is "zoom"? How exactly does this accelerate the grid search? 

3 Can this package be used to optimize "multi objective functions" with "constraints"?

4) Can this package be used to optimize functions that do not have derivatives (i.e. derivative free optimization)? I.e. can this be used instead of Particle Swarm Optimization, Genetic Algorithm?

Thanks!

**Comment by yukai-yang** [comment]
Hello!

Thank you for the comments! And sorry for the late reply! Just answer the questions in the following:

1. it is the standard grid search with some extension, definitely not random.
2. "zoom" means "zoom in". Yes, the algorithm can "zoom in" in the sense that it will take a closer look at the neighbourhood of some points if the optimum is believed to be somewhere around there.
3. I think yes, because the "constraints" in most cases can be regarded as "boundaries", and then we don't need to consider the points outside the "boundaries".
4. Definitely yes. The algorithm does not rely on derivatives (derivative free optimization).
